import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Health</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>Health</h1>
        </div>
      </main>
    </>
  );
};

export default Home;
